
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                # - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      tests:
        - assert_table_not_empty
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: t2_id_payments
      description: "{{ doc( 'payment_desc' ) }}"
      columns:
          - name: payment_method
            description: "The methods clients used for payment service"
            tests:
                - validate_datatype:
<<<<<<< HEAD
                    expected_datatype: TEXT

=======
                    expected_datatype: TEXT
>>>>>>> b24104e0c27e46f51027ecdb016addf9875ce03f
